'use client'

import './globals.css'
import { Inter } from 'next/font/google'
import { QueryClientProvider,QueryClient } from 'react-query'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'CineBase',
  description: 'Generated by create next app',
}

const queryclient = new QueryClient()

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <QueryClientProvider client={queryclient}>
      <body className={inter.className}>{children}</body>
      </QueryClientProvider>
    </html>
  )
}
