import './globals.css'
import { Inter } from 'next/font/google'
import Queryclientprovider from './Queryclientprovider'
import { SpeedInsights } from '@vercel/speed-insights/next';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'CineBase',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
      <Queryclientprovider>
        <html lang="en">
            <body className='bg-[#F7F8FF]'>
              {children}
              <SpeedInsights/>
            </body>
        </html>
      </Queryclientprovider>
  )
}
