import './globals.css'
import { Inter } from 'next/font/google'
import Queryclientprovider from './Queryclientprovider'
import Providers from './Providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'CineBase',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
      <Queryclientprovider>
        <html lang="en">
            <body>
              <Providers>
              {children}
              </Providers>
            </body>
        </html>
      </Queryclientprovider>
  )
}
